"""empty message

Revision ID: 881075c00bc7
Revises: d94b2db1e5a9
Create Date: 2021-12-08 15:28:39.999252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '881075c00bc7'
down_revision = 'd94b2db1e5a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
